"use client"
import { type FormEvent } from "react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import type { ServiceStatus } from "../types"
export type CategoryForm = { name: string; description: string; displayOrder: string; status: ServiceStatus }
export function CategoryFormDialog({ open, editing, values, submitting, onChange, onOpenChange, onSubmit }: { open: boolean; editing: boolean; values: CategoryForm; submitting: boolean; onChange: (value: CategoryForm) => void; onOpenChange: (open: boolean) => void; onSubmit: (event: FormEvent) => void }) { const update = <K extends keyof CategoryForm>(key: K, value: CategoryForm[K]) => onChange({ ...values, [key]: value }); return <Dialog open={open} onOpenChange={(value) => !submitting && onOpenChange(value)}><DialogContent><DialogHeader><DialogTitle>{editing ? "Editar categoria" : "Nova Categoria"}</DialogTitle><DialogDescription>Organize os serviços do catálogo sem alterar suas associações.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><div className="space-y-2"><Label htmlFor="category-name">Nome</Label><Input id="category-name" required maxLength={120} value={values.name} onChange={(e) => update("name", e.currentTarget.value)} /></div><div className="space-y-2"><Label htmlFor="category-description">Descrição (opcional)</Label><Textarea id="category-description" maxLength={500} value={values.description} onChange={(e) => update("description", e.currentTarget.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="category-order">Ordem</Label><Input id="category-order" type="number" min={0} step={1} value={values.displayOrder} onChange={(e) => update("displayOrder", e.currentTarget.value)} /></div><div className="space-y-2"><Label>Status</Label><Select value={values.status} onValueChange={(value: ServiceStatus) => update("status", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ACTIVE">Ativa</SelectItem><SelectItem value="INACTIVE">Inativa</SelectItem></SelectContent></Select></div></div><DialogFooter><Button type="button" variant="outline" disabled={submitting} onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={submitting}>{submitting ? "Salvando..." : "Salvar categoria"}</Button></DialogFooter></form></DialogContent></Dialog> }
