"use client"
import { useMemo, useState } from "react"
import { Pencil, Plus, Search } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { formatBRL, reaisToCents, safeApiMessage } from "../helpers"
import type { CatalogService, ServicePackage } from "../types"
type Props = { packages: ServicePackage[]; services: CatalogService[]; reload: () => Promise<void> }
const empty = { name: "", description: "", price: "", order: "0", serviceIds: [] as string[] }
export function PackagesPanel({ packages, services, reload }: Props) {
 const [query,setQuery]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<ServicePackage|null>(null),[busy,setBusy]=useState<string|null>(null),[form,setForm]=useState(empty)
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("pt-BR");return q?packages.filter(p=>`${p.name} ${p.description??""} ${p.services.map(s=>s.name).join(" ")}`.toLocaleLowerCase("pt-BR").includes(q)):packages},[packages,query])
 const begin=(p?:ServicePackage)=>{setEditing(p??null);setForm(p?{name:p.name,description:p.description??"",price:(p.priceCents/100).toFixed(2).replace(".",","),order:String(p.displayOrder),serviceIds:p.services.map(s=>s.id)}:empty);setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();const priceCents=reaisToCents(form.price),displayOrder=Number(form.order);if(!form.name.trim()||priceCents===null||!Number.isSafeInteger(displayOrder)||displayOrder<0||form.serviceIds.length<2)return toast.error("Informe nome, preco, ordem e ao menos dois servicos.");setBusy("form");try{const r=await fetch(editing?`/api/service-packages/${editing.id}`:"/api/service-packages",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,description:form.description||null,priceCents,displayOrder,serviceIds:form.serviceIds})});if(!r.ok)return toast.error(safeApiMessage(r.status));await reload();setOpen(false);toast.success(editing?"Combo atualizado.":"Combo criado.")}catch{toast.error("Nao foi possivel conectar ao servidor.")}finally{setBusy(null)}}
 async function toggle(p:ServicePackage){if(busy)return;setBusy(p.id);try{const r=await fetch(`/api/service-packages/${p.id}`,{method:p.status==="ACTIVE"?"DELETE":"PUT",headers:{"Content-Type":"application/json"},...(p.status==="INACTIVE"?{body:JSON.stringify({status:"ACTIVE"})}:{})});if(!r.ok)return toast.error(safeApiMessage(r.status));await reload();toast.success(p.status==="ACTIVE"?"Combo inativado.":"Combo reativado.")}catch{toast.error("Nao foi possivel conectar ao servidor.")}finally{setBusy(null)}}
 return <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Combos e pacotes</h3><p className="text-sm text-muted-foreground">Agrupe servicos com valor promocional.</p></div><Button onClick={()=>begin()}><Plus aria-hidden="true"/>Novo Combo</Button></div><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true"/><Input className="pl-9" aria-label="Buscar combo" placeholder="Buscar combo..." value={query} onChange={e=>setQuery(e.currentTarget.value)}/></div>{packages.length===0?<div className="rounded-lg border border-dashed border-border/60 p-10 text-center text-sm text-muted-foreground">Nenhum combo cadastrado.</div>:filtered.length===0?<div role="status" className="rounded-lg border border-dashed border-border/60 p-8 text-center text-sm text-muted-foreground">Nenhum combo corresponde a busca.</div>:<div className="grid gap-3">{filtered.map(p=><article key={p.id} className="rounded-xl border border-border/60 bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-3"><h4 className="font-semibold">{p.name}</h4><span className="text-xs">{p.status==="ACTIVE"?"Ativo":"Inativo"}</span><Switch checked={p.status==="ACTIVE"} disabled={busy===p.id} aria-busy={busy===p.id} aria-label={`${p.status==="ACTIVE"?"Inativar":"Reativar"} combo ${p.name}`} onCheckedChange={()=>void toggle(p)}/></div>{p.description&&<p className="text-sm text-muted-foreground">{p.description}</p>}</div><div className="text-right"><span className="text-xs text-muted-foreground line-through">{formatBRL(p.originalPriceCents)}</span><strong className="ml-2 text-lg text-primary">{formatBRL(p.priceCents)}</strong><p className="text-xs text-muted-foreground">Economia {formatBRL(p.originalPriceCents-p.priceCents)} · {p.durationMinutes} min</p></div></div><div className="mt-3 flex flex-wrap gap-2">{p.services.map(s=><span key={s.id} className="rounded bg-muted px-2 py-1 text-xs">{s.name}</span>)}</div><div className="mt-2 flex items-center justify-between text-xs text-muted-foreground"><span>Ordem {p.displayOrder}</span><Button variant="ghost" size="sm" onClick={()=>begin(p)}><Pencil aria-hidden="true"/>Editar</Button></div></article>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{editing?"Editar combo":"Novo combo"}</DialogTitle><DialogDescription>Selecione ao menos dois servicos ativos.</DialogDescription></DialogHeader><div className="my-5 space-y-3"><Label htmlFor="combo-name">Nome</Label><Input id="combo-name" value={form.name} onChange={e=>setForm({...form,name:e.currentTarget.value})}/><Label htmlFor="combo-desc">Descricao</Label><Input id="combo-desc" value={form.description} onChange={e=>setForm({...form,description:e.currentTarget.value})}/><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="combo-price">Preco promocional</Label><Input id="combo-price" value={form.price} onChange={e=>setForm({...form,price:e.currentTarget.value})}/></div><div><Label htmlFor="combo-order">Ordem</Label><Input id="combo-order" value={form.order} onChange={e=>setForm({...form,order:e.currentTarget.value})}/></div></div><fieldset><legend className="mb-2 text-sm font-medium">Servicos</legend><div className="max-h-48 space-y-2 overflow-auto rounded border p-3">{services.filter(s=>s.status==="ACTIVE").map(s=><label key={s.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.serviceIds.includes(s.id)} onChange={()=>setForm({...form,serviceIds:form.serviceIds.includes(s.id)?form.serviceIds.filter(id=>id!==s.id):[...form.serviceIds,s.id]})}/>{s.name}</label>)}</div></fieldset></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={busy==="form"}>Salvar</Button></DialogFooter></form></DialogContent></Dialog></section>
}
