import { Skeleton } from "@/components/ui/skeleton"
import { SidebarTrigger } from "@/components/ui/sidebar"

const skeletonClass = "motion-reduce:animate-none"

function ServiceCardSkeleton() {
  return <div className="rounded-xl border border-border/60 bg-card/80 p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1 space-y-2"><Skeleton className={`${skeletonClass} h-5 w-2/5`} /><Skeleton className={`${skeletonClass} h-3 w-4/5`} /><Skeleton className={`${skeletonClass} h-5 w-24`} /></div><div className="space-y-2"><Skeleton className={`${skeletonClass} ml-auto h-6 w-20`} /><Skeleton className={`${skeletonClass} ml-auto h-3 w-14`} /></div></div><div className="mt-4 flex items-center justify-between border-t border-border/50 pt-3"><div className="flex gap-3"><Skeleton className={`${skeletonClass} h-3 w-16`} /><Skeleton className={`${skeletonClass} h-3 w-20`} /></div><div className="flex gap-2"><Skeleton className={`${skeletonClass} h-8 w-16`} /><Skeleton className={`${skeletonClass} h-8 w-24`} /></div></div></div>
}

function TeamCardSkeleton() {
  return <div className="rounded-xl border border-border/60 bg-card/80 p-4"><div className="flex items-center gap-3"><Skeleton className={`${skeletonClass} size-11 rounded-full`} /><div className="min-w-0 flex-1 space-y-2"><Skeleton className={`${skeletonClass} h-4 w-1/2`} /><Skeleton className={`${skeletonClass} h-3 w-1/3`} /></div><Skeleton className={`${skeletonClass} size-6 rounded-md`} /></div><div className="mt-4 flex gap-2"><Skeleton className={`${skeletonClass} h-6 w-20`} /><Skeleton className={`${skeletonClass} h-6 w-24`} /></div><Skeleton className={`${skeletonClass} mt-4 h-8 w-full`} /></div>
}

export function ServicesLoading({ visible }: { visible: boolean }) {
  return <div aria-hidden="true" className={`min-h-screen p-4 transition-opacity duration-200 motion-reduce:transition-none sm:p-6 lg:p-8 ${visible ? "opacity-100" : "opacity-0"}`}><div className="mx-auto max-w-[90rem] space-y-7"><header className="flex items-start gap-3"><SidebarTrigger className="mt-1 shrink-0" /><div className="w-full max-w-2xl space-y-2"><Skeleton className={`${skeletonClass} h-8 w-3/5 max-w-md`} /><Skeleton className={`${skeletonClass} h-4 w-4/5 max-w-xl`} /></div></header><div className="grid gap-6 lg:grid-cols-[minmax(0,3fr)_minmax(18rem,2fr)]"><section className="min-w-0 lg:pr-6"><div className="flex items-center justify-between gap-4"><div className="space-y-2"><Skeleton className={`${skeletonClass} h-6 w-48`} /><Skeleton className={`${skeletonClass} h-3 w-56`} /></div><Skeleton className={`${skeletonClass} h-9 w-32`} /></div><div className="mt-4 flex gap-5 border-y border-border/50 py-3">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className={`${skeletonClass} h-3 w-16`} />)}</div><div className="mt-5 flex gap-5 border-b border-border/60 pb-3"><Skeleton className={`${skeletonClass} h-4 w-32`} /><Skeleton className={`${skeletonClass} h-4 w-24`} /><Skeleton className={`${skeletonClass} h-4 w-20`} /></div><Skeleton className={`${skeletonClass} mt-5 h-9 w-full`} /><div className="mt-4 grid gap-3"><ServiceCardSkeleton /><ServiceCardSkeleton /><ServiceCardSkeleton /></div></section><aside className="min-w-0 border-t border-border/50 pt-6 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><div className="space-y-2"><Skeleton className={`${skeletonClass} h-6 w-24`} /><Skeleton className={`${skeletonClass} h-3 w-44`} /></div><div className="mt-5 space-y-3"><TeamCardSkeleton /><TeamCardSkeleton /></div></aside></div></div></div>
}
