import { beforeEach, describe, expect, it, vi } from "vitest"
import { expectJson, jsonRequest } from "../helpers/route-assertions"
import { prismaMock } from "../setup/prisma-mock"
import { ownerSession, professionalBarberSession, superAdminSession } from "../setup/session-fixtures"
const { getSessionMock } = vi.hoisted(() => ({ getSessionMock: vi.fn() }))
vi.mock("@/lib/auth/session", () => ({ getSession: getSessionMock }))
import { GET, POST } from "@/app/api/service-packages/route"
import { DELETE, PUT } from "@/app/api/service-packages/[id]/route"
const context = (id="pkg-1") => ({ params: Promise.resolve({ id }) })
const service = (id:string, priceCents=2000) => ({ id, priceCents })
const fullService = (id:string, priceCents=2000, durationMinutes=30) => ({ id, name:id, priceCents, durationMinutes, status:"ACTIVE", category:null })
const pkg = (status="ACTIVE") => ({ id:"pkg-1",name:"Combo",description:null,priceCents:3000,displayOrder:0,status,items:[{displayOrder:0,service:fullService("s1")},{displayOrder:1,service:fullService("s2",2000,20)}] })
const valid = { name:"Combo",priceCents:3000,displayOrder:0,serviceIds:["s1","s2"] }
function allow(){ getSessionMock.mockResolvedValue(ownerSession); prismaMock.barbershopUser.findFirst.mockResolvedValue({id:"member"}) }
function transaction(){ prismaMock.$transaction.mockImplementation(async (callback:any)=>callback({servicePackage:prismaMock.servicePackage,servicePackageItem:prismaMock.servicePackageItem})) }
describe("API administrativa de combos",()=>{
 beforeEach(()=>{allow();transaction()})
 it.each([[null,401],[superAdminSession,403],[professionalBarberSession,403]])("bloqueia %s sem consultar ou mutar negócio",async(session,status)=>{getSessionMock.mockResolvedValue(session);await expectJson(await POST(jsonRequest("http://x","POST",valid)),status);expect(prismaMock.barbershopUser.findFirst).not.toHaveBeenCalled();expect(prismaMock.service.findMany).not.toHaveBeenCalled();expect(prismaMock.$transaction).not.toHaveBeenCalled()})
 it("bloqueia owner sem membership ou com barbearia inativa",async()=>{prismaMock.barbershopUser.findFirst.mockResolvedValue(null);await expectJson(await GET(),403);expect(prismaMock.barbershopUser.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({barbershop:{status:"ACTIVE"}})}));expect(prismaMock.servicePackage.findMany).not.toHaveBeenCalled()})
 it("cria combo válido no tenant da sessão",async()=>{prismaMock.service.findMany.mockResolvedValue([service("s1"),service("s2")]);prismaMock.servicePackage.create.mockResolvedValue(pkg());const body=await expectJson(await POST(jsonRequest("http://x","POST",{...valid,barbershopId:"attacker"})),201);expect(body).toMatchObject({originalPriceCents:4000,durationMinutes:50});expect(prismaMock.servicePackage.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({barbershopId:ownerSession.barbershopId,items:{create:[{serviceId:"s1",displayOrder:0},{serviceId:"s2",displayOrder:1}]}})}))})
 it("usa o formato nested real e normaliza o payload reproduzido",async()=>{const payload={name:"Combo + degradê + sobrancelha ",description:null,priceCents:7000,displayOrder:0,serviceIds:["00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000002"]};prismaMock.service.findMany.mockResolvedValue(payload.serviceIds.map(id=>service(id,4000)));prismaMock.servicePackage.create.mockImplementation(async(args:any)=>{for(const item of args.data.items.create){if("barbershopId" in item||"packageId" in item)throw new Error("Unknown argument in nested create")}return pkg()});await expectJson(await POST(jsonRequest("http://x","POST",payload)),201);expect(prismaMock.servicePackage.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({name:"Combo + degradê + sobrancelha",description:null,priceCents:7000,items:{create:[{serviceId:payload.serviceIds[0],displayOrder:0},{serviceId:payload.serviceIds[1],displayOrder:1}]}})}))})
 it.each([[{...valid,serviceIds:["s1"]},"dois"],[{...valid,serviceIds:["s1","s1"]},"dois"]])("recusa menos de dois serviços distintos",async(body,message)=>{const result=await expectJson(await POST(jsonRequest("http://x","POST",body)),400);expect(result).toEqual({message:expect.stringContaining(message)});expect(prismaMock.service.findMany).not.toHaveBeenCalled()})
 it.each(["inexistente","outro tenant","inativo"])("recusa serviço %s",async()=>{prismaMock.service.findMany.mockResolvedValue([service("s1")]);await expectJson(await POST(jsonRequest("http://x","POST",valid)),400);expect(prismaMock.service.findMany).toHaveBeenCalledWith(expect.objectContaining({where:{barbershopId:ownerSession.barbershopId,id:{in:["s1","s2"]},status:"ACTIVE"}}));expect(prismaMock.$transaction).not.toHaveBeenCalled()})
 it("recusa preço acima da soma",async()=>{prismaMock.service.findMany.mockResolvedValue([service("s1",1000),service("s2",1000)]);await expectJson(await POST(jsonRequest("http://x","POST",{...valid,priceCents:2001})),400);expect(prismaMock.$transaction).not.toHaveBeenCalled()})
 it("sanitiza conflito de nome",async()=>{prismaMock.service.findMany.mockResolvedValue([service("s1"),service("s2")]);prismaMock.$transaction.mockRejectedValue({code:"P2002",message:"secret"});expect(await expectJson(await POST(jsonRequest("http://x","POST",valid)),409)).toEqual({message:"Ja existe um combo com este nome."})})
 it("mantém erro interno do POST sanitizado",async()=>{prismaMock.service.findMany.mockResolvedValue([service("s1"),service("s2")]);prismaMock.$transaction.mockRejectedValue(new Error("PrismaClientValidationError com dados internos"));expect(await expectJson(await POST(jsonRequest("http://x","POST",valid)),500)).toEqual({message:"Erro interno do servidor."})})
 it("edita e substitui itens atomicamente",async()=>{prismaMock.servicePackage.findFirst.mockResolvedValue(pkg());prismaMock.service.findMany.mockResolvedValue([service("s1"),service("s3")]);prismaMock.servicePackageItem.deleteMany.mockResolvedValue({count:2});prismaMock.servicePackageItem.createMany.mockResolvedValue({count:2});prismaMock.servicePackage.update.mockResolvedValue({...pkg(),name:"Novo"});await expectJson(await PUT(jsonRequest("http://x","PUT",{name:"Novo",serviceIds:["s1","s3"]}),context()),200);expect(prismaMock.servicePackageItem.deleteMany).toHaveBeenCalledBefore(prismaMock.servicePackageItem.createMany);expect(prismaMock.servicePackageItem.createMany).toHaveBeenCalledWith({data:expect.arrayContaining([expect.objectContaining({serviceId:"s3"})])})})
 it("preserva itens se serviceIds não é enviado",async()=>{prismaMock.servicePackage.findFirst.mockResolvedValue(pkg());prismaMock.servicePackage.update.mockResolvedValue({...pkg(),name:"Novo"});await expectJson(await PUT(jsonRequest("http://x","PUT",{name:"Novo"}),context()),200);expect(prismaMock.service.findMany).not.toHaveBeenCalled();expect(prismaMock.servicePackageItem.deleteMany).not.toHaveBeenCalled();expect(prismaMock.servicePackageItem.createMany).not.toHaveBeenCalled()})
 it("isola outro tenant",async()=>{prismaMock.servicePackage.findFirst.mockResolvedValue(null);await expectJson(await PUT(jsonRequest("http://x","PUT",{name:"Novo"}),context("other")),404);expect(prismaMock.servicePackage.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:"other",barbershopId:ownerSession.barbershopId}}));expect(prismaMock.$transaction).not.toHaveBeenCalled()})
 it("inativa idempotentemente",async()=>{prismaMock.servicePackage.findFirst.mockResolvedValue(pkg());prismaMock.servicePackage.update.mockResolvedValue(pkg("INACTIVE"));await expectJson(await DELETE(jsonRequest("http://x","DELETE",{}),context()),200);expect(prismaMock.servicePackage.update).toHaveBeenCalledTimes(1);prismaMock.servicePackage.findFirst.mockResolvedValue(pkg("INACTIVE"));prismaMock.servicePackage.update.mockClear();await expectJson(await DELETE(jsonRequest("http://x","DELETE",{}),context()),200);expect(prismaMock.servicePackage.update).not.toHaveBeenCalled()})
 it("reativa pelo PUT preservando itens",async()=>{prismaMock.servicePackage.findFirst.mockResolvedValue(pkg("INACTIVE"));prismaMock.servicePackage.update.mockResolvedValue(pkg());await expectJson(await PUT(jsonRequest("http://x","PUT",{status:"ACTIVE"}),context()),200);expect(prismaMock.servicePackageItem.deleteMany).not.toHaveBeenCalled();expect(prismaMock.servicePackage.update).toHaveBeenCalledWith(expect.objectContaining({data:{status:"ACTIVE"}}))})
 it("sanitiza erro interno",async()=>{prismaMock.servicePackage.findMany.mockRejectedValue(new Error("database secret"));expect(await expectJson(await GET(),500)).toEqual({message:"Erro interno do servidor."})})
})
